name: celiapp
description: AplicaciÃ³n para productos sin gluten
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.0
  provider: ^6.0.0
  google_maps_flutter: ^2.1.8

flutter:
  uses-material-design: true

  assets:
    - assets/logo.PNG
